### ISSUE TITLE
Incompatible   Cannot open

### ISSUE THREAD

**Issue by Lvbuqing** [kookob/toolset#1]
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64

report errors：Toolset plugin incompatible with this version

Toolset-version：2022.7.1

**Comment by kookob** [comment]
ok, I will check it. Thanks

**Comment by kookob** [comment]
I have updated a version: 2022.9.1, can you try the new one now?

**Comment by Lvbuqing** [comment]
Thanks, I'll try it now

**Comment by Lvbuqing** [comment]
没有效果，还是一样
No effect, still the same

**Comment by kookob** [comment]
不应该啊，IDE和插件用账号登录激活的吗？

**Comment by Lvbuqing** [comment]
正儿八经的账号激活

**Comment by Lvbuqing** [comment]
![image](https://user-images.githubusercontent.com/32841009/188781788-020f0233-5f85-48d2-8795-206e447d1442.png)
![image](https://user-images.githubusercontent.com/32841009/188781866-9884a96e-feae-467c-9de9-c79688784a96.png)

**Comment by kookob** [comment]
插件激活窗口那边帮我截图看下？这版本不应该不兼容
![image](https://user-images.githubusercontent.com/3116606/188782076-e060c899-4a5a-4740-b9bb-171dde61a854.png)

**Comment by Lvbuqing** [comment]
![image](https://user-images.githubusercontent.com/32841009/188783588-d4a02352-27b1-49bb-8d3e-3c4a6f28a208.png)
没有显示

**Comment by kookob** [comment]
那是还没激活，插件也需要独立激活一下。
