### ISSUE TITLE
Java error in Toolset panel

### ISSUE THREAD

**Issue by BabakAmini** [kookob/toolset#2]
I installed the latest version of the Toolset plugin on PyCharm 2023.1 Build #PY-231.8109.91 and I'm facing the following error on Convert, Encrypt, HttpServer, Regex, and WebSocket tabs:

![image](https://user-images.githubusercontent.com/85762931/228960003-4fa4684b-e425-457c-bdd8-6a3d362d919e.png)

Restarting PyCharm and reinstalling the plugin don't help at all.

**Comment by kookob** [comment]
Yes, I have encountered the same error as well due to the changes in the new IDE version API. I am currently attempting to fix it.
Thank you.

**Comment by BabakAmini** [comment]
You're welcome. I just started my 30-day trial yesterday and hope you resolve this issue soon. Would you mind specifying an approximate time you need to handle this?

**Comment by kookob** [comment]
A new version will be released this weekend, but it is expected that the official reviewer will approve it on Monday when they return to work. The estimated time for approval is before next Tuesday.

**Comment by kookob** [comment]
The new version 2023.4.1 has been released. You can try updating it.
And here is a 50% discount code for thank you: `327FD-ELBJX-QY9JJ-EQRK5-CVKHC`
I hope you like it.

**Comment by BabakAmini** [comment]
I appreciate that. Now everything is working.
