### ISSUE TITLE
Request for VS code extension

### ISSUE THREAD

**Issue by Claire** [kookob/toolset#3]
I love this plug in on intellij but have to switch to VS code, is there a VS code version of this plugin as an extension ? or any plans to create one or do you know of any similar equivalent ones to use?

**Comment by kookob** [comment]
Thank you for you love.
Currently, there are no similar plugin for VSCode, but there is a plan to do so in the future if there is time.
However, there are many alternative applications you can try.
For example:
https://www.u.tools/
https://he3.app/en/
Or some online tools:
https://www.sojson.com/
https://onlinetools.com/
I hope these can help you.
