### ISSUE TITLE
让插件可以由工具栏唤起

### ISSUE THREAD

**Issue by ZHOUXING1997** [kookob/toolset#4]
插件可以被添加到工具栏。
现在是搜不到的，只能添加插件的某个能力，而不是被被唤起窗口

![image](https://github.com/kookob/toolset/assets/33240857/026b6863-1e29-4003-854f-3bb9bfa72e2c)
![image](https://github.com/kookob/toolset/assets/33240857/db3c0c06-0db6-45b7-a75a-3352e5dedcda)
![image](https://github.com/kookob/toolset/assets/33240857/1a8aa9db-acd1-4924-a894-d6a5d7afcce0)

**Comment by kookob** [comment]
![image](https://github.com/kookob/toolset/assets/3116606/39017ce4-87f0-4e85-8573-dca8a8050ab3)
唤醒一般是直接点击状态栏旁边的图标，你是有需要从上面工具栏激活窗口的需求？
有需要这功能是可以加的

**Comment by ZHOUXING1997** [comment]
侧边栏的工具实在太多了，如果可以从工具栏激活那会更好~&nbsp;


周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 晚上7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kookob/toolset] 让插件可以由工具栏唤起 (Issue #4)





 

 唤醒一般是直接点击状态栏旁边的图标，你是有需要从上面工具栏激活窗口的需求？
 有需要这功能是可以加的

**Comment by kookob** [comment]
收到，下个版本加一下

**Comment by ZHOUXING1997** [comment]
赞
&nbsp;


周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 晚上7:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kookob/toolset] 让插件可以由工具栏唤起 (Issue #4)






收到，下个版本加一下

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了该线程。消息ID:< koob /工具集/问题/ 4 / ***@***.***与&gt;.

**Comment by kookob** [comment]
2023.11.1版本已经发布，支持添加一个激活action，你可以自己配置一下，默认没显示：
https://plugins.jetbrains.com/plugin/14384-toolset/versions/stable/437285

**Comment by ZHOUXING1997** [comment]
我已经升级并添加了。非常nice。
时间工具那里要不要加一个时区的选项呢？
增加一个 `esc` 按键关闭窗口的监听？




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kookob/toolset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kookob/toolset] 让插件可以由工具栏唤起 (Issue #4)





 
2023.11.1版本已经发布，支持添加一个激活action，你可以自己配置一下，默认没显示：
 https://plugins.jetbrains.com/plugin/14384-toolset/versions/stable/437285

**Comment by kookob** [comment]
时间工具确实有必要加时间，这个后续加上。
esc关闭窗口，就是关闭toolset面板吗？

**Comment by ZHOUXING1997** [comment]
时间工具那里加一个时间格式转义的 format 规则怎么样？




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kookob/toolset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kookob/toolset] 让插件可以由工具栏唤起 (Issue #4)





 
时间工具确实有必要加时间，这个后续加上。
 esc关闭窗口，就是关闭toolset面板吗？

**Comment by kookob** [comment]
好的，感谢建议，我考虑下

**Comment by kookob** [comment]
Toolset plugin新版本(2023.12.1)已经发布，增加了时间时区的设置和格式配置，请更新使用，谢谢你的建议。

**Comment by ZHOUXING1997** [comment]
已经在更新了，辛苦辛苦~




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kookob/toolset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kookob/toolset] 让插件可以由工具栏唤起 (Issue #4)





 
Toolset plugin新版本(2023.12.1)已经发布，增加了时间时区的设置和格式配置，请更新使用，谢谢你的建议。
