### ISSUE TITLE
convert.json: json -> yaml

### ISSUE THREAD

**Issue by ZHOUXING1997** [kookob/toolset#5]
`{
	"demoKey": [
		{
			"interval": 9223372036854775807,
			"limit": 9223372036854775807
		}
	]
}`

现在的转化
![image](https://github.com/kookob/toolset/assets/33240857/f02f98d1-beeb-4abf-9f83-82ee449b44b6)

理想的
![image](https://github.com/kookob/toolset/assets/33240857/6ad7e6e2-1ffd-460b-b7b2-bdc951e0ea77)

**Comment by ZHOUXING1997** [comment]
https://www.json2yaml.com/
这个网站的是对的

**Comment by kookob** [comment]
用的第三方工具包，这种格式好像不是规范的json，后续看下能不能做处兼容处理。（不一定能修正）
谢谢反馈

**Comment by ZHOUXING1997** [comment]
额，不规范的 json？指的是？

最好可以修复~~~

**Comment by kookob** [comment]
好的，下个版本修复

**Comment by kookob** [comment]
这个修复很久了，我关了哈。
